use_frameworks!

platform :ios, '10.0'

target 'CYUIComponents_Example' do
  pod 'CYUIComponents', :path => '../'

  target 'CYUIComponents_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
